swagger: "2.0"
info:
  description: "A super cool endpoint for rendering a json list of tracks."
  version: "1.0.0"
  title: "YOUR PROJECT NAME"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "localhost:3000"
basePath: "/api/v1"
schemes:
- "http"
paths: